/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [103.59KB] > /Users/younghong/code/ThreeJS/butterfly_effect_lp/project/public/models/butterfly/scene-transformed.glb [232.18KB] (-124%)
Author: eb78 (https://sketchfab.com/E.A.Cornell)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/ulysses-butterfly-1155effb97564974aa0553db3d5eed57
Title: Ulysses Butterfly
*/
"use client"
import React, {useEffect} from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Butterfly(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/butterfly/scene-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  // console.log('actions ', actions)

  useEffect(() => {
    actions.fly.timeScale = 0.15
    actions.fly.play()
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.UlyssesButterfly_mat} skeleton={nodes.Object_7.skeleton} scale={0.694} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/butterfly/scene-transformed.glb')
