import { Inter, Bruno_Ace } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const brunoAce = Bruno_Ace({
  weight: "400", // ✅ required
  variable: "--font-bruno",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${brunoAce.variable}`}>
      <body>{children}</body>
    </html>
  );
}

